---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: .

  post_tasks:
    - name: Check if NTP is enabled
      ansible.builtin.command: timedatectl show -p NTP
      register: ntp_status
      changed_when: false
